backend:
  name: git-gateway
  branch: master

site_url: https://benbooth.dev
logo_url: https://benbooth.dev/images/bb-logo.png

publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

collections:
  - name: 'blog'
    label: 'Blog Posts'
    label_singular: 'Blog Post'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'blog-post' }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Publish Date', widget: 'date' }
      - { name: 'description', label: 'Description', widget: 'text' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
      - { name: 'tags', label: 'Tags', widget: 'list' }
